### ISSUE TITLE
使用 docker 部署，连接拒绝

### ISSUE THREAD

**Issue by BaoYuanY** [zhenorzz/goploy#109]
我使用 docker 部署 goploy 日志显示连接被拒绝，但是我使用 DataGrip 连接 MySQL 可以正常连接，下面是我部署细节
```yaml
docker run -it \
    --name=goploy \
    --env=DB_HOST=******** \
    --env=DB_USER=**** \
    --env=DB_USER_PASSWORD=***** \
    --env=DB_NAME=goploy \
    -v /path/to/.ssh:/root/.ssh \
    -v /path/to/hosts:/etc/hosts \
    -v /path/to/repository:/opt/goploy/repository \
    -p 153:80 \
    zhenorzz/goploy
 ```

<img width="809" alt="image" src="https://github.com/zhenorzz/goploy/assets/93755812/817a5025-a778-4e49-92ba-92bb2d1d9361">

<img width="323" alt="image" src="https://github.com/zhenorzz/goploy/assets/93755812/2d84f3c4-7312-40fa-b059-9644e23fd118">

**但是日志显示**
```
Status: Downloaded newer image for zhenorzz/goploy:latest

   ______            __           
  / ____/___  ____  / /___  __  __
 / / __/ __ \/ __ \/ / __ \/ / / /
/ /_/ / /_/ / /_/ / / /_/ / /_/ / 
\____/\____/ .___/_/\____/\__, /  
          /_/            /____/   1.4.1

The configuration file already exists, no need to reinstall (if you need to reinstall, please back up the database `goploy` first, delete the .env file, then restart.)
dial tcp :3306: connect: connection refused
Start at 2024-06-07 09:48:08.842475707 +0000 UTC m=+0.003753733
goploy -h for more help
Current pid:   1
Config Loaded: /opt/goploy/.env
Log:           stdout
Listen:        80
Running...
New release available
https://github.com/zhenorzz/goploy/releases/tag/v1.17.1
ERROR: 2024/06/07 09:48:09 MonitorTask.go:23: get monitor list error, detail:dial tcp :3306: connect: connection refused
ERROR: 2024/06/07 09:48:10 MonitorTask.go:23: get monitor list error, detail:dial tcp :3306: connect: connection refused
ERROR: 2024/06/07 09:48:11 MonitorTask.go:23: get monitor list error, detail:dial tcp :3306: connect: connection refused
ERROR: 2024/06/07 09:48:12 MonitorTask.go:23: get monitor list error, detail:dial tcp :3306: connect: connection refused
ERROR: 2024/06/07 09:48:13 MonitorTask.go:23: get monitor list error, detail:dial tcp :3306: connect: connection refused
```

**Comment by zhenorzz** [comment]
图中的版本的 1.4.1，
你 需要 pull 最新的 tag

**Comment by BaoYuanY** [comment]
```
[root@iZuf6elmadjdb2bobqlilnZ docker]# docker run -it \
>     --name=goploy \
>     --env=DB_HOST=********* \
>     --env=DB_USER=******* \
>     --env=DB_USER_PASSWORD=****** \
>     --env=DB_NAME=goploy \
>     -v /path/to/.ssh:/root/.ssh \
>     -v /path/to/hosts:/etc/hosts \
>     -v /path/to/repository:/opt/goploy/repository \
>     -p 153:80 \
>     zhenorzz/goploy:1.17.1
Unable to find image 'zhenorzz/goploy:1.17.1' locally
1.17.1: Pulling from zhenorzz/goploy
d25f557d7f31: Pull complete 
25b2f38701b6: Pull complete 
5d42d386c0b0: Pull complete 
2418c4627997: Pull complete 
68a0b34a13f2: Pull complete 
283f341163af: Pull complete 
27fe8d70feef: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:abff6ca289686827c6251d0c219a695a6b4901d864b4b96a0ce96c4efc1940b4
Status: Downloaded newer image for zhenorzz/goploy:1.17.1

   ______            __           
  / ____/___  ____  / /___  __  __
 / / __/ __ \/ __ \/ / __ \/ / / /
/ /_/ / /_/ / /_/ / / /_/ / /_/ / 
\____/\____/ .___/_/\____/\__, /  
          /_/            /____/   1.17.1

Start to install the database...
panic: sql: unknown driver "" (forgotten import?)

goroutine 1 [running]:
main.install()
        C:/Users/Administrator/Documents/docker-env/project/go/goploy/cmd/server/main.go:195 +0x4de
main.main()
        C:/Users/Administrator/Documents/docker-env/project/go/goploy/cmd/server/main.go:107 +0xaa
[root@iZuf6elmadjdb2bobqlilnZ docker]#
```

现在我重新部署 上述错误提示，下述是我的服务器数据
```
[root@iZuf6elmadjdb2bobqlilnZ docker]# hostnamectl
   Static hostname: iZuf6elmadjdb2bobqlilnZ
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 77e79816427b49ffa5657acfd45ae660
           Boot ID: d62fb47499da432f95b35a38f12d2e55
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.114.2.el7.x86_64
      Architecture: x86-64
[root@iZuf6elmadjdb2bobqlilnZ docker]# 
```

**Comment by zhenorzz** [comment]
更新一下最新1.17.2修复了
